jenkins-master:
  image: reg.cnrancher.com/pipeline/jenkins:2.60.2_tool
  ports:
    - ${JENKINS_PORT}:8080
    - ${JENKINS_SLAVEPORT}:50000
  restart: always
  environment:
    - JENKINS_SLAVE_AGENT_PORT=50000
    - JENKINS_HOME=/var/jenkins_home
  volumes_from:
    - jenkins-boot
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  labels:
    io.rancher.sidekicks: jenkins-boot
    io.rancher.container.create_agent: true
    io.rancher.container.agent.role: environment
jenkins-boot:
  image: reg.cnrancher.com/pipeline/jenkins_home:2.60.2_1
  volumes:
    - ${VOLUME_DIR}:/var/jenkins_home
  labels:
    io.rancher.container.start_once: true
jenkins-slave:
  image: reg.cnrancher.com/pipeline/jenkins-slave
  restart: always
  links:
    - jenkins-master
  environment:
    - SLAVE_EXECUTORS: ${EXECUTORS}
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  labels:
    io.rancher.container.create_agent: true
    io.rancher.container.agent.role: environment
pipeline-server:
  image: reg.cnrancher.com/rancher/pipeline:5071
  links:
    - jenkins-master
  environment:
    - JENKINS_ADDRESS=http://jenkins-master:8080
    - JENKINS_USER=admin
    - JENKINS_TOKEN=admin
    - HOST_NAME=${HOST_NAME}
  ports:
    - ${HOST_PORT}:60081
  labels:
    io.rancher.container.create_agent: true
    io.rancher.container.agent.role: environment
