version: '2'
catalog:
  name: CICD
  version: 0.1.0
  description: "Rancher CICD"
  minimum_rancher_version: v1.6.8
  questions:
    - variable: SLAVES
      type: "int"
      default: "0"
      label: "# of slaves"
      description: "How many jenkins slaves to run ci tasks."
    - variable: EXECUTORS
      type: "int"
      default: "2"
      label: "# of executors"
      description: "How many executors on a jenkins slave"
    - variable: HOST_LABEL
      label: "Host with Label to put pipeline components on"
      description: |
        Run pipeline components on Host with specific labels. 
        Example: 'pipeline=true'
      required: false
      default: ""
      type: "string"
services:
#{{- if ne .Values.SLAVES "0" }} 
  jenkins-slave:
    scale: ${SLAVES}
#{{- end }} 
