version: '2'
catalog:
  name: CICD
  version: 0.6.0-r2.0-v3
  description: "rancher compose desc"
  upgrade_from: "<=0.4.0"
  questions:
    - variable: SLAVES
      type: "int"
      default: "0"
      label: "# of slaves"
      description: "How many jenkins slaves to run ci tasks."
    - variable: EXECUTORS
      type: "int"
      default: "2"
      label: "# of executors"
      description: "How many executors on a jenkins slave"
    - variable: JENKINS_PORT
      type: "int"
      label: "Jenkins Public Port"
      description: "Public port for Jenkins master's http port.for DEBUG purpose,remove when release."
    - variable: VOLUME_DRIVER 
      description: "Volume driver to use for jenkins home volume"
      label: "Volume driver"
      required: true
      default: "local"
      type: enum
      options:
        - local
    - variable: HOST_LABEL
      label: "Host with Label to put pipeline components on"
      description: |
        Run pipeline components on Host with specific labels. 
        Example: 'pipeline=true'
      required: false
      default: ""
      type: "string"
services:
#{{- if ne .Values.SLAVES "0" }} 
  jenkins-slave:
    scale: ${SLAVES}
#{{- end }} 
