name: CICD # Name of the Catalog Entry
description: Hello CICD
  # Description of the Catalog Entry
version: 4.0.0 # Version of the Catalog to be used
category: Infra # Category to be used for searching catalog entries
maintainer: Aaron # The maintainer of the catalog entry
license: MIT # The license
