name: CICD # Name of the Catalog Entry
description: (Experimental) Rancher CICD
  # Description of the Catalog Entry
version: 0.1.0 # Version of the Catalog to be used
category: Continuous Integration # Category to be used for searching catalog entries
Support: Maintained by community members # The maintainer of the catalog entry
